SET CAINC=C:\Keil\ARM\INC\Philips\;C:\Keil\ARM\INC\
SET CALIB=C:\Keil\ARM\LIB
SET CPU_TYPE=LPC2148
SET CPU_VENDOR=Philips
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x00B71B00
C:\Keil\ARM\BIN\AA @Startup._ia
C:\Keil\ARM\BIN\CA @app.__i
C:\Keil\ARM\BIN\CA @gsm.__i
C:\Keil\ARM\BIN\CA @lib.__i
C:\Keil\ARM\BIN\CA @main.__i
C:\Keil\ARM\BIN\CA @rtc.__i
C:\Keil\ARM\BIN\CA @uart.__i
C:\Keil\ARM\BIN\CA @key.__i
C:\Keil\ARM\BIN\CA @timer.__i
C:\Keil\ARM\BIN\CA @lcd.__i
C:\Keil\ARM\BIN\CA @gsm_app.__i
C:\Keil\ARM\BIN\LA @TIMER_~1.LNP
"C:\Keil\ARM\BIN\OHA" "Timer_Capture _mode" 
